kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pvmigrate
rules:
  - apiGroups: [ "" ]
    resources:
      - persistentvolumes
    verbs:
      - list
      - get
      - update
      - delete
  - apiGroups: [ "" ]
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - delete
  - apiGroups: [ "" ]
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get
      - delete
      - create
  - apiGroups: [ "storage.k8s.io" ]
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - update
      - delete
  - apiGroups: [ "apps" ]
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - update
  - apiGroups: [ "apps" ]
    resources:
      - replicasets
    verbs:
      - get
