name: release-go

on:
  push:
    tags:
    - "v*.*.*"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make test


  goreleaser:
    runs-on: ubuntu-latest
    needs:
    - test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - uses: actions/setup-go@v1
      with:
        go-version: "1.16"

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist --config deploy/.goreleaser.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update new pvmigrate version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.40
      with:
        krew_template_file: deploy/krew/pvmigrate.yaml
